#ifndef BFM_PSYQ_COMPAT_H
#define BFM_PSYQ_COMPAT_H

/* Psy-Q -> PsyCross / HLE compatibility layer for the native lane.
 *
 * bfm_psyq_compat.def (generated by tools/psyq_callsites.py) lists every Psy-Q
 * entry point the game code calls, with a status:
 *   PSYCROSS  a wrapper over PsyCross (psyq_psycross.c, needs PsyCross)
 *   HLE       our own C (bfm_psyq_compat.c)
 *   STUB      no host version: the wrapper refuses and the interpreter runs
 *             the retail code from the user's disc
 *
 * Wrapper ABI: int wrapper(uint32_t *r) over the guest o32 register file
 * (a0-a3 = r[4..7], further args at guest sp+0x10, result in r[2]).
 * Return 1 = done, 0 = refused (nothing changed).
 *
 * Guest memory: bfm_psyq_set_ram(phys0, size) with the host address of guest
 * physical 0 (the native lane's design (a): (void *)0x80000000); addresses are
 * masked to physical, and the 1 KiB scratchpad at 0x1F800000 is separate. */

#include <stddef.h>
#include <stdint.h>

#include "../bfm_plat_renderer.h"

typedef enum BfmPsyqStatus {
    BFM_PSYQ_PSYCROSS = 1,
    BFM_PSYQ_HLE = 2,
    BFM_PSYQ_STUB = 3
} BfmPsyqStatus;

typedef int (*BfmPsyqFn)(uint32_t *r);

typedef struct BfmPsyqEntry {
    uint32_t pc;
    const char *name;
    uint8_t status;              /* BfmPsyqStatus as generated */
    uint8_t argc;
    uint8_t returns;
    uint8_t available;           /* 1 if fn is a real implementation in this build */
    BfmPsyqFn fn;
} BfmPsyqEntry;

size_t bfm_psyq_table(const BfmPsyqEntry **out);
const BfmPsyqEntry *bfm_psyq_find(uint32_t pc);
/* Runs the entry for pc on r; 0 when there is none or it refused. */
int bfm_psyq_call(uint32_t pc, uint32_t *r);

void bfm_psyq_set_ram(void *phys0, size_t size);
void bfm_psyq_set_scratchpad(void *base);

/* o32 argument n (0-based; n >= 4 from the guest stack). */
uint32_t bfm_psyq_arg(const uint32_t *r, unsigned n);
/* Host pointer for [addr, addr+len) of guest RAM or scratchpad; NULL if out of range. */
void *bfm_psyq_ptr(uint32_t addr, uint32_t len);

typedef struct BfmPsyqStats {
    uint64_t ot_packets;
    uint64_t prims;
    uint64_t unknown_commands;
    uint64_t refused;
    uint32_t last_unknown_code;
} BfmPsyqStats;
void bfm_psyq_stats(BfmPsyqStats *out);
void bfm_psyq_reset(void);

/* GP0 packet decoding (DrawOTag): decodes the command words of one packet
 * into prims; returns prims written (<= max). *tpage carries the draw state
 * across packets: bits 0-13 the E1 texpage (textured polygons update it),
 * bit 14 E6 mask-set, bit 15 E6 mask-check. */
size_t bfm_psyq_decode_packet(const uint32_t *words, size_t nwords, uint16_t *tpage,
                              BfmPlatPrim *out, size_t max);

/* ---- GTE bridge ---------------------------------------------------------
 * There is one cop2 register file: PsyCross's process-wide gteRegs bank,
 * which port-int's gte_owner already leases for the interpreter. PsyCross's
 * libgte functions work on the same bank, so the libgte wrappers need no
 * copying. They only have to respect the owner's lease: begin() must confirm
 * that this thread owns the lease, CU2 is enabled and no cop2 operation is
 * in progress, and mark the owner busy; end() clears that mark and accounts
 * the work (commands issued). Without a bridge every GTE-state wrapper refuses,
 * so the interpreter runs the retail code. Stateless wrappers (ratan2,
 * RotMatrix{X,Y,Z,YXZ}) don't touch the bank and don't need the bridge. */
typedef struct BfmPsyqGteBridge {
    int (*begin)(void *user);                     /* 1 = may use gteRegs now */
    void (*end)(void *user, uint32_t commands);   /* commands = GTE ops issued */
    void *user;
} BfmPsyqGteBridge;

/* NULL removes the bridge. */
void bfm_psyq_set_gte_bridge(const BfmPsyqGteBridge *bridge);
int bfm_psyq_gte_begin(void);
void bfm_psyq_gte_end(uint32_t commands);

/* Stateless libgte helpers exact to the retail code (bfm_psyq_libgte.c),
 * on guest-layout MATRIX bytes. rotmatrix reads the game's own sin/cos table
 * in guest RAM (0 if it isn't mapped). */
int bfm_psyq_rotmatrix(const int16_t angles[3], uint8_t *matrix32);
void bfm_psyq_scalematrix(uint8_t *matrix32, const int32_t v[3]);
void bfm_psyq_transmatrix(uint8_t *matrix32, const int32_t v[3]);

/* libgs's OT link (func_80051EA0), for packet builders in other files:
 * slot = org + (pri - offset)*4; returns the address after the packet. */
int bfm_psyq_gs_link(uint32_t pkt, uint32_t ot, uint32_t pri, uint8_t len, uint32_t *next);

/* The stub every STUB entry uses: refuses. */
int bfm_psyq_stub(uint32_t *r);

/* HLE / PsyCross wrappers (declared for the table). */
#define BFM_PSYQ(pc, name, status, argc, returns, wrapper) int wrapper(uint32_t *r);
#include "bfm_psyq_compat.def"
#undef BFM_PSYQ

#endif
