#!/usr/bin/env python3
"""Sony PsyQ ranges of the SLUS-00726 main executable, and the port check.

`build` derives config/psyq_ranges.txt (vram ranges and segment names only)
from the vendor splat layout (vendor/bfm-decomp/config/splat.us.exe.yaml):
every code subsegment named snd*, lib*, apicard* or gap is Sony library
code; sgap_* and the rest are game code.

`check` fails when a decomp source whose vram lies in a PsyQ range is
compiled into a port target. The port gets PsyQ behaviour from PsyCross
(MIT) or our own HLE, never from SDK objects or decompiled PsyQ C.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "config/psyq_ranges.txt"
EXE_TEXT, EXE_BASE = 0x800, 0x80010000
PSYQ = re.compile(r"^(snd|lib|apicard|gap$)")


def build(splat):
    segs = []
    for m in re.finditer(r"^\s*- \[(0x[0-9A-Fa-f]+), (\w+|\.\w+), (\w+)\]", splat.read_text(), re.M):
        segs.append((int(m.group(1), 16), m.group(2), m.group(3)))
    end_marker = re.search(r"^\s*- \[(0x[0-9A-Fa-f]+)\]\s*$", splat.read_text(), re.M)
    rows = []
    for i, (off, kind, name) in enumerate(segs):
        if kind != "c":
            continue
        nxt = segs[i + 1][0] if i + 1 < len(segs) else int(end_marker.group(1), 16)
        if PSYQ.match(name):
            rows.append((off - EXE_TEXT + EXE_BASE, nxt - EXE_TEXT + EXE_BASE, name))
    merged = []
    for lo, hi, name in rows:
        merged.append((lo, hi, name))
    lines = ["# Sony PsyQ code in the SLUS-00726 main executable: <start> <end> <segment>.",
             "# Generated by tools/psyq_manifest.py build from the vendor splat layout.",
             "# Addresses only; no code. Game-code gaps (sgap_*) are excluded."]
    lines += [f"{lo:08x} {hi:08x} {name}" for lo, hi, name in merged]
    MANIFEST.write_text("\n".join(lines) + "\n")
    print(f"{len(merged)} PsyQ ranges, {sum(h - l for l, h, _ in merged)} bytes")


def ranges():
    out = []
    for line in MANIFEST.read_text().splitlines():
        if line and not line.startswith("#"):
            lo, hi, name = line.split()
            out.append((int(lo, 16), int(hi, 16), name))
    return out


def psyq_segment(vram, table=None):
    for lo, hi, name in table or ranges():
        if lo <= vram < hi:
            return name
    return None


def source_vram(path):
    m = re.match(r"([0-9a-fA-F]{8})", Path(path).name)
    if not m or "src/main/" not in str(path).replace("\\", "/"):
        return None
    return int(m.group(1), 16)


def check(sources, allow):
    table = ranges()
    allowed = set()
    if allow and Path(allow).is_file():
        allowed = {l.split()[0] for l in Path(allow).read_text().splitlines()
                   if l.strip() and not l.startswith("#")}
    bad, pending = [], []
    for src in sources:
        vram = source_vram(src)
        if vram is None:
            continue
        seg = psyq_segment(vram, table)
        if seg:
            rel = str(Path(src).resolve().relative_to(ROOT)) if Path(src).is_absolute() else src
            (pending if rel in allowed else bad).append((rel, seg))
    for rel, seg in pending:
        print(f"psyq-check: PENDING replacement {rel} (PsyQ {seg})", file=sys.stderr)
    for rel, seg in bad:
        print(f"psyq-check: FORBIDDEN {rel} is Sony PsyQ code ({seg}); use PsyCross/HLE", file=sys.stderr)
    return 1 if bad else 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build")
    b.add_argument("--splat", type=Path,
                   default=ROOT / "vendor/bfm-decomp/config/splat.us.exe.yaml")
    c = sub.add_parser("check")
    c.add_argument("--allow", help="file of repo-relative sources pending replacement")
    c.add_argument("sources", nargs="*")
    args = ap.parse_args()
    if args.cmd == "build":
        build(args.splat)
        return 0
    return check(args.sources, args.allow)


if __name__ == "__main__":
    sys.exit(main())
